Added new task for render trigger deployment

diff --git a/.github/workflows/03_python_flask_pipeline.yml b/.github/workflows/03_python_flask_pipeline.yml
--- a/.github/workflows/03_python_flask_pipeline.yml
+++ b/.github/workflows/03_python_flask_pipeline.yml
@@ -24,17 +24,65 @@ jobs:
                  pip install -r requirements.txt
               continue-on-error: false
               working-directory: modules/03.Python_Flask_Pipeline
+              id: install-dependencies
 
 
             - name: Run Flake8 Linting
               run: flake8 .
               continue-on-error: false
               working-directory: modules/03.Python_Flask_Pipeline
+              id: run-flake8
 
             - name: Py test
               run: pytest test_app.py
               continue-on-error: false
               working-directory: modules/03.Python_Flask_Pipeline
+              id: py-test
+
+            - name: Trigger Render deployment
+              run: |
+                curl --request POST \
+                    --url https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys \
+                    --header 'accept: application/json' \
+                    --header 'authorization: Bearer ${{ secrets.RENDER_API_KEY }}' \
+                    --header 'content-type: application/json'
+              continue-on-error: false
+              id: deploy-render
+
+            # Success/Failure message after key steps
+            - name: Check Success/Failure Messages
+              if: always()  
+              run: |
+                if [ ${{ steps.install-dependencies.outcome }} == 'success' ]; then
+                  echo "✅ Dependencies installed successfully!"
+                else
+                  echo "❌ Failed to install dependencies!"
+                  exit 1
+                fi
+                
+                if [ ${{ steps.run-flake8.outcome }} == 'success' ]; then
+                  echo "✅ Flake8 linting passed!"
+                else
+                  echo "❌ Flake8 linting failed!"
+                  exit 1
+                fi
+                
+                if [ ${{ steps.py-test.outcome }} == 'success' ]; then
+                  echo "✅ PyTest passed!"
+                else
+                  echo "❌ PyTest failed!"
+                  exit 1
+                fi
+                
+                
+                if [ ${{ steps.deploy-render.outcome }} == 'success' ]; then
+                  echo "✅ Successfully triggered Render deployment!"
+                else
+                  echo "❌ Failed to trigger Render deployment!"
+                  exit 1
+                fi
+              continue-on-error: false
+
 
               
 
